# Generated by Django 5.0.6 on 2024-06-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_user_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
