# Generated by Django 5.0.6 on 2024-06-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_user_balance_alter_user_pendingbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='HourSalary',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
