# Generated by Django 5.0.6 on 2024-06-20 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_user_hoursalary_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pendingbalance',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Approve', models.BooleanField(default=False)),
                ('Status', models.CharField(default='Open', max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('Topic', models.CharField(max_length=50)),
                ('RequestDesc', models.TextField(max_length=300)),
                ('Budget', models.IntegerField()),
                ('Category', models.CharField(max_length=100)),
                ('Decline', models.BooleanField(default=False)),
                ('PostDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offerdesc', models.TextField(max_length=100)),
                ('Price', models.IntegerField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('RequestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.request')),
            ],
            options={
                'unique_together': {('UserID', 'RequestID')},
            },
        ),
        migrations.CreateModel(
            name='Request_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
                ('RequestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.request')),
            ],
            options={
                'unique_together': {('RequestID', 'skill')},
            },
        ),
    ]
