# Generated by Django 5.0.6 on 2024-06-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='Decline',
            field=models.BooleanField(default=False),
        ),
    ]
