# Generated by Django 5.0.6 on 2024-06-29 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_offer_decline'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='PostDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
