# Generated by Django 5.0.6 on 2024-06-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_offer_postdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('message', models.TextField()),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
    ]
