# Generated by Django 5.0.6 on 2024-06-29 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='PostDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
