# Generated by Django 5.0.6 on 2024-07-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_complaint_postdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
