# Generated by Django 5.0.6 on 2024-07-06 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_remove_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='Type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.request'),
        ),
    ]
