# Generated by Django 5.0.6 on 2024-07-07 17:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_user_facebook_user_website_user_secweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Type', models.CharField(max_length=50)),
                ('Amount', models.FloatField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requestID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.request')),
            ],
        ),
    ]
