# Generated by Django 5.0.6 on 2024-07-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_user_profit_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Type',
            new_name='Topic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Facebook',
        ),
        migrations.RemoveField(
            model_name='user',
            name='WebSite',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secweb',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
