# Generated by Django 5.0.6 on 2024-07-07 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_rename_type_transaction_topic_remove_user_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='UserID',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Admin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='OfferOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OfferOwner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='RequestOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='RequestOwner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
