# Generated by Django 5.0.6 on 2024-07-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_remove_transaction_userid_transaction_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='pendingbalance',
            field=models.FloatField(default=0.0),
        ),
    ]
