# Generated by Django 5.0.6 on 2024-07-10 01:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeAndWithdrow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('Title', models.TextField()),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
