# Generated by Django 5.0.6 on 2024-07-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0027_chargeandwithdrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeandwithdrow',
            name='Type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
