# Generated by Django 5.0.6 on 2024-07-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_chargeandwithdrow_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='DeclineReason',
            field=models.TextField(default='', null=True),
        ),
    ]
