# Generated by Django 5.0.6 on 2024-07-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0029_request_declinereason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
