# Generated by Django 5.0.6 on 2024-07-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0031_alter_complaint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Type',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
