# Generated by Django 5.0.6 on 2024-07-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0032_alter_complaint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeandwithdrow',
            name='Successfull',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
