# Generated by Django 5.0.6 on 2024-07-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0033_chargeandwithdrow_successfull'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Faculty',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
