# Generated by Django 5.0.6 on 2024-07-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0034_user_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='BirthDate',
            field=models.DateField(null=True),
        ),
    ]
