# Generated by Django 5.0.6 on 2024-07-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0036_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='feedback',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
